### ISSUE TITLE
Not Working anymore

### ISSUE THREAD

**Issue by Callen151** [maletsna/Discord-Rich-Presence-NVSE#1]
Been a while since I played NV so I don't know when exactly it broke but I get the following error in discord_integration.log

> DiscordRPC version 1 passed NVSE Query.
> DiscordRPC loaded.
> Initializing connection to discord
> Connected to user [Username]
> Discord error:  errorcode 1000
> Discord error:  errorcode 1000
> Discord error:  errorcode 1000
> Discord error:  errorcode 1000
> Discord error:  errorcode 1000
> Discord error:  errorcode 1000
> Discord error:  errorcode 1000
> Discord error:  errorcode 1000
> Discord error:  errorcode 1000
> Discord error:  errorcode 1000
> Discord error:  errorcode 1000

**Comment by maletsna** [comment]
Someone mentioned that restarting the PC helped fix Fallout 3 version back in November. This uses a deprecated library so there's a chance that Discord changed something in their API. I probably won't look into it, though.

**Comment by Callen151** [comment]
I'll give the restart a go. That's a shame though :( thanks for all your mods
